1.2/Dockerfile
Just did a version bump after this morning's release from José.
=> Update to Elixir 1.2.4.

.travis.yml, 1.2/slim/Dockerfile, 1.3/Dockerfile, README.md
https://github.com/elixir-lang/elixir/releases/tag/v1.2.5
and switch to maintain both `erlang:18` based (to be regular developer friendly)
and `erlang:18-slim` based, this should resolve #3 also resolves #4 @tuvistavie @cgarciae
=> Update to Elixir 1.2.5

1.2/Dockerfile, 1.2/slim/Dockerfile, 1.3/Dockerfile, README.md
thanks merging elixir-lang/elixir#4412 :heart:
=> version update: Elixir v1.3.0-rc.0 on Erlang 19.0-rc2

1.2/Dockerfile, 1.2/slim/Dockerfile, generate-stackbrew-library.sh
the `generate-stackbrew-library.sh` is inspired from python and with minor modifications.
https://github.com/docker-library/python/blob/master/generate-stackbrew-library.sh
=> generate new manifest file format for official-images

1.3/slim/Dockerfile, generate-stackbrew-library.sh
for docker-library/official-images#1882
=> use precompiled elixir 1.3

1.3/Dockerfile, 1.3/slim/Dockerfile
Tested locally, SHA generated with `sha256sum Precompiled.zip`.
Cheers!
=> Upgrades elixir to 1.3.1

.travis.yml, 1.4/Dockerfile, 1.4/onbuild/Dockerfile, README.md
=> for the bleeding edge elixir:1.4.0-dev image

1.3/Dockerfile, 1.3/slim/Dockerfile
Tested locally, SHA generated with `sha256sum Precompiled.zip`.
Cheers :beers:!
=> Upgrades elixir to 1.3.3

1.3/Dockerfile, 1.3/slim/Dockerfile
=> Upgrades elixir to 1.3.4

1.4/Dockerfile, 1.4/slim/Dockerfile
Making it official. Happy release day!
=> upgrades elixir 1.4.0 to official release

1.4/Dockerfile, 1.4/slim/Dockerfile
=> Upgrades elixir to 1.4.4

1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.5/slim/Dockerfile
just version bump. for https://github.com/elixir-lang/elixir/releases/tag/v1.5.1
=> Upgrades elixir to 1.5.1

1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.5/slim/Dockerfile
Ready to update `official-images` as well.
=> Upgrades elixir to 1.5.3

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile, generate-stackbrew-library.sh
https://elixir-lang.org/blog/2018/01/17/elixir-v1-6-0-released/
=> Update to 1.6 and make latest

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile
Ready to update `official-images` when this is merged.
=> Upgrades elixir to 1.6.1

generate-stackbrew-library.sh
for docker-library/official-images#3956
this resolves #47
=> Build as a multi-arch image

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile
=> Upgrades elixir to v1.6.3

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile
https://github.com/elixir-lang/elixir/releases/tag/v1.6.4
=> Upgrades elixir to v1.6.4

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile
https://github.com/elixir-lang/elixir/releases/tag/v1.6.5
Ready to submit a PR for [`official-images`](https://github.com/sdwolfz/official-images/commit/97dd28bdccc4805989197c37f8aade031432f95e) when this is merged!
=> Upgrades elixir to 1.6.5

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.6/slim/Dockerfile
👋 
I gave the update a shot.
Everything works fine on my machine, so I hope it also does for you 😃
=> Upgrades to elixir 1.6.6 and erlang 21

1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.7/slim/Dockerfile
=> the elixir v1.7.0-rc.1

1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.7/slim/Dockerfile
* Update to 1.7 images to 1.7.2
=> Update to 1.7 images to 1.7.2

1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.7/slim/Dockerfile
=> Update 1.7 images to 1.7.3

generate-stackbrew-library.sh
(Matches https://github.com/docker-library/official-images/pull/4644)
=> Remove 1.3 from generate-stackbrew-library.sh

1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.7/slim/Dockerfile
=> version up: v1.7.4

.travis.yml, 1.7/otp-21.2-alpine/Dockerfile, 1.7/otp-21.2/Dockerfile, 1.8/otp-21.2-alpine/Dockerfile, 1.8/otp-21.2/Dockerfile, generate-stackbrew-library.sh
=> Introduce OTP-21.2 to versions 1.7 and 1.8

generate-stackbrew-library.sh
erlang/docker-erlang-otp#82  erlang/docker-erlang-otp#211
=> add arm32v7 architecture for alpine version
